In [3]:
type(())

tuple

In [5]:
import numpy as np
from matplotlib import pyplot as plt

In [3]:
type([])

list

In [6]:
type({'x'})

set

In [1]:
x = {1,2,3,4,5}
y = {1,3,5}

# Intersección
x & y
x.intersection(y)

# Unión
x | y 
x.union(y)

# Diferencia
x - y
x.difference(y)

# Diferencia simétrica
x ^ y



{2, 4}

In [8]:
matrix = np.random.randint(0,15, size=(5,5))
print(matrix)



[[ 5 10 12  3 12]
 [13 10  3  9  3]
 [ 0  3  0  5  6]
 [14  7  6  3  7]
 [ 8  0 14  6 12]]
