In [2]:
import numpy as np

In [8]:
np.array([[1,2,3],[1,2,3]])

array([[1, 2, 3],
       [1, 2, 3]])

In [10]:
# convert a list o an array
np.array(list(range(10)), dtype=np.int16)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [24]:
x = np.ones((10,10), dtype=np.int16)

In [21]:
np.eye(5,dtype=np.int16)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [25]:
    # transpose x
x.T


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [26]:
# random numbers array
np.random.random(10,10)

array([[0.12782802, 0.01648436, 0.322633  , 0.86786331, 0.19151532,
        0.03773334, 0.31556051, 0.881175  , 0.39242755, 0.66873865],
       [0.46912857, 0.1352678 , 0.01584712, 0.79152667, 0.87810641,
        0.49758616, 0.65996581, 0.32516183, 0.31645486, 0.25213306],
       [0.11234248, 0.39158525, 0.38220533, 0.03779327, 0.29258318,
        0.071325  , 0.07058783, 0.00796424, 0.98877843, 0.25830384],
       [0.12728482, 0.15588198, 0.34414079, 0.65526796, 0.90012445,
        0.55864355, 0.88486997, 0.02013055, 0.19711654, 0.15340682],
       [0.83523308, 0.77517587, 0.07140764, 0.32120945, 0.72890316,
        0.45870402, 0.17886655, 0.35079002, 0.16501262, 0.55675376],
       [0.25137181, 0.52344644, 0.92334899, 0.10797921, 0.6913239 ,
        0.64191894, 0.66348426, 0.54199928, 0.10007426, 0.05206267],
       [0.89570041, 0.8540498 , 0.74995265, 0.20159681, 0.35648814,
        0.56714397, 0.17531703, 0.7006952 , 0.18201607, 0.44665182],
       [0.49318919, 0.24963799, 0.1555239